CREATE TABLE "USER_KANBAN_BOARD" (
 "ID" TEXT,
 "NAME" TEXT NOT NULL UNIQUE,
 "PROJECT_ID" TEXT NOT NULL,
 "USER_ID" TEXT NOT NULL,
 "DATA" TEXT,
 PRIMARY KEY("ID"),
 FOREIGN KEY("PROJECT_ID") REFERENCES "PROJECT"("ID"),
 FOREIGN KEY("USER_ID") REFERENCES "USER"("ID")
);
CREATE UNIQUE INDEX "UNIQUE_INDEX_USER_KANBAN_BOARD_USER_ID_PROJECT_ID" ON "USER_KANBAN_BOARD"("USER_ID", PROJECT_ID);
